plugins {
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    group = 'org.digitalmind.buildingblocks.core'
    version = '4.0.0'

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "digitalmind"
            url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
            credentials {
                username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
                password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
            }
        }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.3"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 25
    }
}
