plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}
group 'org.digitalmind.buildingblocks.core'
version '2.0.1'

ext {
    lombokVersion = '1.18.32'
    springOpenapiVersion = '2.6.0'
    swaggerAnnotationsVersion = '2.2.25'
}
java {
    sourceCompatibility = "21"
    targetCompatibility = "21"
}
bootJar {
    enabled = false
}
jar {
    archiveBaseName = "dynamic-cache-resolver"
    enabled = true
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"

    implementation "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

publishing {
    repositories {
        maven {
            name = "digitalmind"
            url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
            credentials {
                username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
                password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
            }
        }
    }
    publications {
        dynamicCacheResolver(MavenPublication) {
            from components.java
        }
    }
}
