package org.digitalmind.buildingblocks.core.jpaauditor.entity.enumeration;

public enum FileUrlStatus {
    TEMPORARY("A file uploaded with temporary file name - autogenerated with date and uuid"),
    REFERRED("A file referred from an external storage system"),
    COPIED("A file copied to the final storage location"),
    FINAL("A file copied to the final location and the cleanup procedures to delete the temporary file were executed");

    private final String description;

    FileUrlStatus(String description) {
        this.description = description;
    }

}
